# Generated by Django 2.2 on 2020-08-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200803_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
