x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "5"

services:
  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    command: postgres -c 'max_connections=500'
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: always
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  web:
    container_name: web
    image: blog-app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./run_django.sh"]
    restart: always
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 8001:8000
    volumes: &app-volumes
      - .:/code/
    env_file: &app-env app/.env
    environment: &app-env-vars
      DATABASE_HOST: postgres
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672
    depends_on: &app-depends
      - postgres
      - rabbitmq

  worker:
    container_name: worker
    image: blog-app
    command: ["./run_celery.sh"]
    restart: always
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 512M
    volumes: *app-volumes
    env_file: *app-env
    environment: *app-env-vars
    depends_on: *app-depends

  beat:
    container_name: beat
    image: blog-app
    command: ["./run_beat.sh"]
    restart: always
    logging: *default-logging
    deploy:
      resources:
        limits:
          memory: 256M
    volumes: *app-volumes
    env_file: *app-env
    environment: *app-env-vars
    depends_on: *app-depends

volumes:
  postgres_data:
