# Generated by Django 2.2 on 2021-09-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='опубликовано в первоисточнике')),
                ('sourse_link', models.URLField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('authors', models.ManyToManyField(blank=True, null=True, to='article.Author')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='article.Tag')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
