# Generated by Django 2.2 on 2021-09-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resourse', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
